# -*- coding: utf-8 -*-
"""btk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dEhiBULvDyfC7D1p6clsvLLT5Ke9s5mc
"""

import numpy as np

prob = np.ones(38)
prob[0] = 0.9
prob[prob == 1] = 0.1/37

np.random.seed(42)

hp = np.random.choice(np.arange(38), size = (10000, 22, 100), p = prob)

import seaborn as sn
import matplotlib.pyplot as plt

hm = sn.heatmap(hp[0])
plt.show()

np.savetxt('test.out', hp[0], delimiter=',')